name: CI/CD .NET 5 App (Ubuntu 22.04 + Docker Build)

on:
  push:
    branches: [ "main" ]

env:
  IMAGE_NAME: schoolsystems

jobs:
  build-and-publish:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET 5 SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '5.0.x'

      - name: Restore dependencies
        run: dotnet restore ./SchoolSystems/SchoolSystems.csproj

      - name: Build project with detailed logs
        run: dotnet build ./SchoolSystems/SchoolSystems.csproj --configuration Release --no-restore -v diag

      - name: Publish project
        run: dotnet publish ./SchoolSystems/SchoolSystems.csproj -c Release -o ./publish -v diag

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:${{ github.sha }} .

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:${{ github.sha }}

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
            docker stop schoolsystems || true
            docker rm schoolsystems || true
            docker run -d -p 8080:80 --name schoolsystems ${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
