name: CI/CD .NET 5 App

on:
  push:
    branches: [ "main" ]

env:
  IMAGE_NAME: schoolsystems

jobs:
  package:
    runs-on: ubuntu-latest
    steps:
      # 1️⃣ Checkout code
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Restore dependencies
      - name: Restore dependencies
        run: dotnet restore

      # 3️⃣ Build project in Release
      - name: Build project
        run: dotnet build --configuration Release --no-restore

      # 4️⃣ Publish artifacts
      - name: Publish project
        run: dotnet publish --configuration Release --output ./publish
        working-directory: ${{ github.workspace }}/SchoolSystems

      # 5️⃣ Upload artifacts
      - name: Upload published artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dotnet-publish
          path: SchoolSystems/publish/*

  build:
    runs-on: ubuntu-latest
    needs: package
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Download published artifacts
      - name: Download published artifacts
        uses: actions/download-artifact@v3
        with:
          name: dotnet-publish
          path: SchoolSystems/publish

      # Docker login
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build Docker image
      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:${{ github.sha }} ./SchoolSystems

      # Push Docker image
      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:${{ github.sha }}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
            docker stop schoolsystems || true
            docker rm schoolsystems || true
            docker run -d -p 80:80 --name schoolsystems ${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:${{ github.sha }}











