name: Build and Dockerize .NET 5 App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  IMAGE_NAME: schoolsystems

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # --- Checkout code ---
    - name: Checkout repository
      uses: actions/checkout@v3

    # --- Debug Info ---
    - name: Show .NET info
      run: dotnet --info

    - name: List project files
      run: ls -la

    - name: Show environment variables
      run: env

    # --- Setup .NET 5 ---
    - name: Setup .NET 5
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '5.0.x'

    # --- Restore & Build ---
    - name: Restore dependencies
      run: dotnet restore

    - name: Build project
      run: dotnet build --configuration Release --no-restore

    # --- Run tests verbose ---
    - name: Run tests
      run: dotnet test --no-build --verbosity detailed

    # --- Docker build only (no push) ---
    - name: Build Docker image
      run: docker build -t ${{ env.IMAGE_NAME }}:latest .



